/*
 * This file is a part of the ImageSpark Downloader project.
 * Minimized by GCC.
 */

window.onload=function(){(function(c){function r(){$("#folder_name_textbox").val(c.folder_name).on("change",function(){c.folder_name=$.trim(this.value)});chrome.downloads.onDeterminingFilename.addListener(function(a,b){c.folder_name&&b({filename:c.folder_name+"/"+a.filename})});$("#download_button").on("click",t);$("#open_folder_button").on("click",u);$("#folder_name_textbox").on("input",function(){$("#open_folder_button").css("display","none")});$("#images_table").on("change","#toggle_all_checkbox",
function(){$("#download_button").prop("disabled",!this.checked);for(var a=0;a<d.length;a++)$("#image"+a).toggleClass("checked",this.checked)}).on("click","img",function(){$(this).toggleClass("checked",!$(this).hasClass("checked"));for(var a=!0,b=!0,e=0;e<d.length&&($("#image"+e).hasClass("checked")?b=!1:a=!1,a||b);e++);$("#download_button").prop("disabled",b);e=$("#toggle_all_checkbox");e.prop("indeterminate",!(a||b));a?e.prop("checked",!0):b&&e.prop("checked",!1)}).on("click",".image_url_textbox",
function(){this.select()}).on("click",".download_image_button",function(){chrome.downloads.download({url:$(this).data("url")});$("#open_folder_button").css("display","block")}).on("click",".open_image_button",function(){chrome.tabs.create({url:$(this).data("url"),active:!1})});chrome.windows.getCurrent(function(a){chrome.tabs.query({active:!0,windowId:a.id},function(b){chrome.tabs.executeScript(b[0].id,{file:"/scripts/get_images.js",allFrames:!0},function(){chrome.runtime.lastError&&$("#loading_error").show()})})})}
function v(){jss.set(".image_buttons_container",{"margin-top":("true"===c.show_image_url?3:-3)+"px"});jss.set("img",{"min-width":c.image_min_width+"px","max-width":c.image_max_width+"px","border-width":c.image_border_width+"px","border-style":"solid","border-color":"#f6f6f6"});jss.set("img.checked",{"border-color":"rgb(33, 150, 243)","box-shadow":"0 5px 35px rgb(33, 150, 243)"});setInterval(function(){$("body").css("padding-top",$("#filters_container").height())},200)}function w(){clearTimeout(m);
m=setTimeout(function(){d=n.slice(0);$("#download_button").prop("disabled",!0);var a=$("#images_table").empty(),b='<tr><th align="left" colspan="'+c.columns+'"><label><input type="checkbox" id="toggle_all_checkbox" />'+chrome.i18n.getMessage("select_all_checkbox")+" ("+d.length+")</label></th></tr>";a.append(b);for(var b=parseInt(c.columns),e=Math.round(1E4/b)/100+"%",x=Math.ceil(d.length/b),h="true"===c.show_image_url,p="true"===c.show_open_image_button,q="true"===c.show_download_image_button,k=
$("<tr></tr>"),m=(h?1:0)+(p?1:0)+(q?1:0)||1,f=0;f<b;f++)k.append('<td colspan="'+m+'" style="min-width: '+c.image_max_width+"px; width: "+e+'; vertical-align: top;"></td>');a.append(k);for(k=0;k<x;k++){if(h||p||q){for(var l=$("<tr></tr>"),f=0;f<b;f++){var g=k*b+f;if(g===d.length)break;h&&l.append('<td><input type="text" class="image_url_textbox" value="'+d[g]+'" readonly /></td>');p&&l.append('<td class="open_image_button" data-url="'+d[g]+'" title="'+chrome.i18n.getMessage("open_image_button_title")+
'">&nbsp;</td>');q&&l.append('<td class="download_image_button" data-url="'+d[g]+'" title="'+chrome.i18n.getMessage("download_image_button_title")+'">&nbsp;</td>')}a.append(l)}l=$("<tr></tr>");for(f=0;f<b;f++){g=k*b+f;if(g===d.length)break;l.append('<td colspan="'+m+'" style="min-width: '+c.image_max_width+"px; width: "+e+'; vertical-align: top; text-align:center; padding-top:5px; padding-bottom:50px;"><img id="image'+g+'" src="'+d[g]+'" /></td>')}a.append(l)}},200)}function t(){function a(){for(var b=
0,a=0;a<d.length;a++)$("#image"+a).hasClass("checked")&&(b++,chrome.downloads.download({url:d[a]}));y(b);0<b&&$("#open_folder_button").css("display","block")}"true"===c.show_download_confirmation?z(a):a()}function u(){var a=$("#folder_name_textbox").val().trim(),a=a.replace(/[\[\]&\/\\#,+()$~%.'":*?<>{}]/g,"");0>=a.length?chrome.downloads.showDefaultFolder():chrome.downloads.search({limit:150,filenameRegex:a+"(\\\\|\\/)",orderBy:["-startTime"]},function(a){0<a.length&&chrome.downloads.show(a[0].id)})}
function z(a){var b=$('<div id = "notification_container">\t\t\t\t  <div>\t\t\t\t\t<hr/>\t\t\t\t\tTake a quick look at your Chrome settings and search for the <b>download location</b>.\t\t\t\t\t<span class="danger">If the <b>Ask where to save each file before downloading</b> option is checked, proceeding might open a lot of popup windows. Are you sure you want to do this?</span>\t\t\t\t  </div>\t\t\t\t  <input type="button" id="yes_button" class="success" value="YES" />\t\t\t\t  <input type="button" id="no_button" class="danger" value="NO" />\t\t\t\t  <label><input type="checkbox" id="dont_show_again_checkbox" />Don\'t show this again</label>\t\t\t\t</div>');
$("#notification_container").length||b.appendTo("#filters_container");$("#yes_button, #no_button").on("click",function(){c.show_download_confirmation=!$("#dont_show_again_checkbox").prop("checked");b.remove()});$("#yes_button").on("click",a)}function y(a){if("true"===c.show_download_notification){var b=$('<div class="success">Downloading '+a+" image"+(1<a?"s":"")+"...</div>").appendTo("#filters_container");A(b,3.5,0,function(){b.remove()})}}function A(a,b,e,d){e||(e=parseInt(c.animation_duration));
var h=function(c){0<b?(b-=.5,c?a.fadeIn(e,function(){h(!1)}):a.fadeOut(e,function(){h(!0)})):d&&d(a)};h(!1)}$("#folder_name_textbox").attr("placeholder",chrome.i18n.getMessage("subfolder_placeholder"));$("#folder_name_textbox").attr("title",chrome.i18n.getMessage("subfolder_title"));$("#open_folder_button").attr("title",chrome.i18n.getMessage("open_folder_button_title"));$("#download_button").attr("value",chrome.i18n.getMessage("download_button_value"));$("#loading_message").html(chrome.i18n.getMessage("loading_message"));
$("#loading_error").html(chrome.i18n.getMessage("loading_error"));var n=[],d=[],B={};chrome.extension.onMessage.addListener(function(a){$.extend(B,a.linkedImages);for(var b=0;b<a.images.length;b++)-1===n.indexOf(a.images[b])&&n.push(a.images[b]);w()});var m;$(function(){r();v()})})(localStorage)};